"""Canonical Pydantic models for PromptSpec data contracts."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SlotType = Literal[
    "role",
    "task",
    "constraint",
    "forbidden",
    "output_format",
    "evidence_rule",
    "strategy",
    "context",
]
SlotSource = Literal["user", "parent", "import", "system"]
ReportStatus = Literal["pass", "fail"]
ValidationSeverity = Literal["info", "warning", "critical"]
TestSuite = Literal["unit", "integration", "scenario", "regression", "e2e", "ralph"]
RalphTaskStatus = Literal["pending", "in_progress", "completed", "blocked"]


class PromptSlot(BaseModel):
    """Source unit of prompt meaning."""

    model_config = ConfigDict(extra="forbid")

    key: str = Field(min_length=1)
    type: SlotType
    value: str
    condition: str | None = None
    priority: int = 100
    source: SlotSource = "user"
    version: int = Field(default=1, ge=1)
    required: bool = True


class PromptStrategy(BaseModel):
    """Strategy fields that select renderer, validator, and inspector behavior."""

    model_config = ConfigDict(extra="forbid")

    render_strategy: str
    validation_strategy: str
    inspection_strategy: str


class PromptSpec(BaseModel):
    """Resolved or unresolved prompt specification."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1)
    title: str = Field(min_length=1)
    parent_id: str | None = None
    slots: list[PromptSlot] = Field(default_factory=list)
    strategy: PromptStrategy
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_unique_slot_keys(self) -> PromptSpec:
        keys = [slot.key for slot in self.slots]
        if len(keys) != len(set(keys)):
            raise ValueError("slot keys must be unique within a PromptSpec")
        return self


class Span(BaseModel):
    """Rendered text span traced to a source slot."""

    model_config = ConfigDict(extra="forbid")

    slot_key: str = Field(min_length=1)
    start: int = Field(ge=0)
    end: int = Field(ge=0)
    text: str

    @model_validator(mode="after")
    def validate_offsets(self) -> Span:
        if self.end < self.start:
            raise ValueError("span end must be greater than or equal to start")
        return self


class RenderedPrompt(BaseModel):
    """Rendered prompt text and source span metadata."""

    model_config = ConfigDict(extra="forbid")

    spec_id: str = Field(min_length=1)
    text: str
    spans: list[Span] = Field(default_factory=list)


class MeaningReport(BaseModel):
    """Schema-bound interpretation of rendered prompt meaning."""

    model_config = ConfigDict(extra="forbid")

    spec_id: str = Field(min_length=1)
    schema_version: int = Field(default=1, ge=1)
    meaning: dict[str, Any]
    uncertainties: list[str] = Field(default_factory=list)
    raw_model: str | None = None


class ValidationIssue(BaseModel):
    """Single validation issue emitted by deterministic validators."""

    model_config = ConfigDict(extra="forbid")

    code: str = Field(min_length=1)
    severity: ValidationSeverity
    slot_key: str | None = None
    message: str = Field(min_length=1)


class ValidationMetrics(BaseModel):
    """Quality metrics attached to a validation report."""

    model_config = ConfigDict(extra="forbid")

    slot_coverage: float = Field(ge=0.0, le=1.0)
    conflict_count: int = Field(ge=0)
    critical_over_generation: int = Field(ge=0)
    meaning_schema_valid: bool


class ValidationReport(BaseModel):
    """Validation result for PromptSpec, RenderedPrompt, and MeaningReport."""

    model_config = ConfigDict(extra="forbid")

    spec_id: str = Field(min_length=1)
    status: ReportStatus
    issues: list[ValidationIssue] = Field(default_factory=list)
    metrics: ValidationMetrics


class TestReport(BaseModel):
    """Report generated by test harness execution."""

    model_config = ConfigDict(extra="forbid")

    report_id: str = Field(min_length=1)
    suite: TestSuite
    status: ReportStatus
    commands: list[str] = Field(default_factory=list)
    artifacts: list[str] = Field(default_factory=list)


class RalphTask(BaseModel):
    """Task executed by the Ralph Loop."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1)
    title: str = Field(min_length=1)
    status: RalphTaskStatus
    source_doc: str = Field(min_length=1)
    acceptance_criteria: list[str] = Field(default_factory=list)
    test_commands: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_completion_contract(self) -> RalphTask:
        if not self.acceptance_criteria:
            raise ValueError("RalphTask requires acceptance criteria")
        if not self.test_commands:
            raise ValueError("RalphTask requires test commands")
        return self


CANONICAL_MODEL_TYPES: tuple[type[BaseModel], ...] = (
    PromptSlot,
    PromptSpec,
    RenderedPrompt,
    MeaningReport,
    ValidationReport,
    TestReport,
    RalphTask,
)


def export_json_schemas() -> dict[str, dict[str, Any]]:
    """Return JSON schemas for all canonical machine-facing models."""

    return {model.__name__: model.model_json_schema() for model in CANONICAL_MODEL_TYPES}

